version: '3.6'
networks:
  internal-net:
   name: workbench_subnet
services:
  backend:
    image: openjdk:8-jre
    container_name: backend
    networks:
      - internal-net
    volumes:
      - ./backend/build/libs:/opt/assets/
    command: java -jar /opt/assets/blog-0.0.1-SNAPSHOT.jar
  db:
    image: postgres:10.5
    container_name: db
    restart: always
    volumes:
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    networks:
      - internal-net
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "4200:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST=ninrod.org
      - NGINX_PORT=80
    networks:
      - internal-net
