version: '3'
services:
  server:
    image: openjdk:8-jre
    volumes:
      - ./build/libs:/opt/assets/
    ports:
      - "8080:8080"
    command: java -jar /opt/assets/blog-0.0.1-SNAPSHOT.jar
  db:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432